version: '3'
services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:80
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD=030119082
      - DRUPAL_DATABASE_NAME=final
    volumes:
      - drupal_data:/bitnami
    depends_on:
      - mariadb
    networks:
      - drupal_network

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami
    networks:
      - drupal_network

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - drupal
    networks:
      - drupal_network

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email yahsi.abdullah@std.izu.edu.tr --agree-tos --no-eff-email --force-renewal -d halkalicocugu.me
    depends_on:
      - nginx
    networks:
      - drupal_network

networks:
  drupal_network:
